# Generated by Django 3.0.3 on 2020-02-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='title',
            field=models.CharField(default='SOME STRING', max_length=250),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='summary',
            field=models.CharField(default='SOME STRING', max_length=250),
        ),
    ]
