# Generated by Django 3.0.3 on 2020-02-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200217_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='projects',
            name='body',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='projects',
            name='summary',
            field=models.CharField(default='', max_length=250),
        ),
    ]
