# Generated by Django 3.0.3 on 2020-02-17 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200217_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='body',
        ),
    ]
