# Generated by Django 3.0.3 on 2020-02-17 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_projects_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='projects',
        ),
    ]
