# Generated by Django 3.0.3 on 2020-02-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='projects',
            name='pub_date',
            field=models.DateTimeField(default=''),
        ),
    ]
