# Generated by Django 3.0.3 on 2020-02-17 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_projects_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='body',
        ),
    ]
