# Generated by Django 3.0.3 on 2020-02-17 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blog_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
    ]
