# Generated by Django 3.0.3 on 2020-03-12 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blog_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='body',
        ),
    ]
